name       : python-gitdb2
version    : 4.0.7
release    : 4
source     :
    - https://github.com/gitpython-developers/gitdb/archive/refs/tags/4.0.7.tar.gz : 2a1a7d43cb6b2fcd919922ca13f4e425836211cd6612598a536665295ce6c46c
license    : BSD-3-Clause
component  : programming.python
summary    : GitDB is a pure-Python git object database
description: |
    GitDB is a pure-Python git object database
builddeps  :
    - git
    - python-nose
    - python-smmap2
rundeps    :
    - python-smmap2
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    mkdir dummyGitRepo
    pushd dummyGitRepo
    git init
    git config user.name 'My Name'
    git config user.email 'my@email.com'
    # Do note that tests want at least 50 commits
    for c in {0..50}; do
        echo $c > $c
        git add $c
        git commit -m "commit $c"
    done
    popd
    export GITDB_TEST_GIT_REPO_BASE=$workdir/dummyGitRepo/.git
    # Test_"pack_writing" is known to fail
    python3 -m nose -v --exclude=test_pack_writing
